### ISSUE TITLE
Can't run: 'Movie' object has no attribute 'load'

### ISSUE THREAD

**Issue by Wohlstand** [nitram509/ascii-telnet-server#10]
Tried for a quick test run the movie, however, script has an error and not working:
```
~/_git_repos/ascii-telnet-server $ python3.6 ascii_telnet_server.py -f ./movies/badapple.txt --stdout -S 80x24 -s 80x25 -r 60
Traceback (most recent call last):
  File "ascii_telnet_server.py", line 199, in <module>
    run_std_out(options.filename, framerate, screen_width, screen_height, frame_width, frame_height)
  File "ascii_telnet_server.py", line 110, in run_std_out
    movie.load(filepath)
AttributeError: 'Movie' object has no attribute 'load'
```

**Comment by ZenithalHourlyRate** [comment]
**Fast (worst) solution**
`git reset 5b69116`

I tested that it can run the movie well. 
No offense to the excellent work done by nitram509.

Debug details:
It seems that nitram509 has removed Movie.load and changed some variable names(from _frame_height/_frame_width to frame_height/frame_width) in classs Movie, thus I can not just simply add Movie.load back from old codes. 

Note that Movie.load is used twice, in ascii_telnet_server.run_std_out and ascii_telnet/ascii_server.py, line 65. Changes should take place at both places.

**Comment by nitram509** [comment]
hi all,
indeed I did started some refactoring an MASTER branch is broken as of now.
this is odd, I admit.
I will roll back my latest changed and derive my work on a DEVELOPMENT branch
and fix MASTER again.

Sorry for the confusion and thank you all for your feedback 👍 

Regards
Martin

**Comment by nitram509** [comment]
done. 
you might want to check again, @Wohlstand ?

**Comment by Wohlstand** [comment]
Will check once I'll reach my workplace

**Comment by Wohlstand** [comment]
Yes, it now works!
