### ISSUE TITLE
Any recommendations to create movies?

### ISSUE THREAD

**Issue by pinpox** [nitram509/ascii-telnet-server#11]
Hi, did you create the movies by hand or are there any tools I can use?

**Comment by nitram509** [comment]
Hi,

I have to admit, I did not create them. See the copyright in the movie itself.
There are a few tools mentioned on Wikipedia:
https://de.wikipedia.org/wiki/ASCII-Art
(see section "Software zum Erstellen von ...").
I hope that helps.

Regards
Martin

**Comment by ZenithalHourlyRate** [comment]
Hi, another developer and I have recently developed a tool called [acm](https://github.com/ZenithalHourlyRate/acm) (AsCii Movie) that converts video to ascii movie, and we can produce the movie in a format ascii-telnet-server can use. You may try it.
