### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by Cabalist** [nitram509/ascii-telnet-server#4]
Hey there!  This project seems pretty inactive but it is cool.  I submitted a Pull request with Python3 support, bug fixes, more modular code, updated README, and some small tests.

**Comment by nitram509** [comment]
Hi Ryan!

Thank you very much for your contribution.
I saw you merged many improvements and even added some changes after pull request.
From what I've briefly read in your summary, this looks great.

Please give me some days to look for it in detail ...

Regards
Martin

**Comment by Cabalist** [comment]
No worries.  Let me know if anything looks unclear.  I'd love to get this packaged up and put on PyPi next.  :)

**Comment by Cabalist** [comment]
Sorry to give you a moving target but I had a long flight yesterday and did more cleanup and renaming that I previously didn't think I had time for.  I have put it on a branch in my repo.  This should wrap it up.  Let me know if you'd like those combined with this pull request or if you would rather review these changes first and then take a look at the new ones.

**Comment by nitram509** [comment]
I've already incorporated you additional branch.
Please check my comment in the PR, the tests fail under some environments.

**Comment by Cabalist** [comment]
Yep.  It looks like I tested for and then inadvertently overlooked one of the Python2/3 gotchas:

In Python2:
```python
> len("Œ") 
2
```

In Python3:

```python
> len("Œ")
1
```

However this is the correct way to do it:

Python2/3
```python
> len(u"Œ")
1
```

I've made the necessary changes.  I am interested in making this completely Unicode compatible because in theory you could get a full color movie that way.

Just imagine:
🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹
🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹
🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹
🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹
🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹
🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹
🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹
🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹
🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹
🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹
🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹🐹

**Comment by Cabalist** [comment]
Also I am not a fan of targeting 3.2.  If it was up to me we should target 3.5+ or at worst 3.4+  

3.2 has too much weird broken stuff.

**Comment by nitram509** [comment]
Hehe, great idea about unicode ;-)

About Python 3.2 - there I'm relaxed. If you're saying it's not worth to support it, just remove it from test env. and make a statement in README, please. So we're transparent.

**Comment by Cabalist** [comment]
Already done.   :)  

I am working on packaging now in a branch as well.  It is a bit of a challenge making sure everything gets put in the right place.

**Comment by nitram509** [comment]
I saw you're improving more and more :-)
Anything worth to merge yet?

**Comment by Cabalist** [comment]
This is a good point to do the merge.  I have some branches that I am floundering around in trying to package it for PyPI but I think here is as good as place as any to put peg in.

Tests are also forthcoming.

**Comment by nitram509** [comment]
Support for Python 3 has landed meanwhile.
